apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
spec:
  ports:
    - port: 80
      targetPort: reddit-port
      protocol: TCP
  selector:
    app: reddit-clone
  type: LoadBalancer
